apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-bad
spec:
  replicas: 1
  selector:
    matchLabels: { app: demo }
  template:
    metadata:
      labels: { app: demo }
    spec:
      containers:
        - name: demo
          image: demo-app:latest
          ports:
            - containerPort: 8000
